name: Test Environment Variables

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: codebuild-test-bucket-cfn-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Test BUCKET_NAME (dynamic ref)
        run: echo "BUCKET_NAME is '$BUCKET_NAME'"
      
      - name: Test BUCKET_ARN (dynamic ref)
        run: echo "BUCKET_ARN is '$BUCKET_ARN'"
      
      - name: Test STATIC_VAR (static value)
        run: echo "STATIC_VAR is '$STATIC_VAR'"
